---
ignored: []
map:
  Em: 09A
  Eb: 05B
  Am: 08A
  Ebm: 02A
  Bb: 06B
  D: 10B
  F#m: 11A
  Bm: 10A
  Gm: 06A
  Abm: 01A
  Fm: 04A
  B: 01B
  Dm: 07A
  Bbm: 03A
  Dbm: 12A
  F#: 02B
  C: 08B
  Cm: 05A
  A: 11B
  G: 09B
  E: 12B
  Db: 03B
  F: 07B
  Ab: 04B
  A#min: 01A
  G#min: 06A
  Fmaj: 07B
  F#min: 11A
  Amin: 08A
